In [18]:
import numpy as np
import open3d as o3d
import cv2 as cv

In [37]:
points = np.load("out/points_0.npy")
colors = np.load("out/colors_0.npy")

In [39]:
colors.shape

(7457, 3)

In [26]:
r = np.arange( 0, 24).reshape(4, 6)
g = np.arange(24, 48).reshape(4, 6)
b = np.arange(48, 72).reshape(4, 6)

rgb = np.stack((r, g, b), axis=2)
roi = np.array([
    [0, 1, 0, 0, 1, 0],
    [1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 0, 1],
], dtype=bool)

In [27]:
np.stack((r, g, b), axis=0)

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71]]])

In [36]:
rgb[roi]

array([[ 1, 25, 49],
       [ 4, 28, 52],
       [ 6, 30, 54],
       [20, 44, 68],
       [21, 45, 69],
       [23, 47, 71]])

In [35]:
np.flip(rgb[roi], axis=1)

array([[49, 25,  1],
       [52, 28,  4],
       [54, 30,  6],
       [68, 44, 20],
       [69, 45, 21],
       [71, 47, 23]])

In [32]:
uvs = np.column_stack(np.where(roi))
print(uvs)

for u, v in uvs:
    print(u, v)

[[0 1]
 [0 4]
 [1 0]
 [3 2]
 [3 3]
 [3 5]]
0 1
0 4
1 0
3 2
3 3
3 5
